### ISSUE TITLE
expose number of active streams

### ISSUE THREAD

**Issue by xiang90** [grpc-ecosystem/go-grpc-prometheus#13]
We used to have a customized gPRC metrics system in etcd. And we want to change that to a more standard one. The only missing metrics from this library is the number of active streams.

In etcd, users might keep long running streams (watchers, lease keepalives). So it is important for us to monitor the number of active streams. Do you think this is a useful one in general?

Thanks!

**Comment by mwitkow** [comment]
@xiang90 this is already possible: `sum(grpc_server_started_total) - sum(grpc_server_handled_total)`. The reason why this was moved to counters from gauges, is that counters are more reliable way to capture such data across scrape periods.

**Comment by mwitkow** [comment]
Or am I missing some requirement that you guys have? :)

**Comment by xiang90** [comment]
@mwitkow Awesome. We already switched etcd metrics to use this library: https://github.com/coreos/etcd/pull/6851.
