### ISSUE TITLE
Prometheus metrics not provisionned using grpc_auth

### ISSUE THREAD

**Issue by nlamirault** [grpc-ecosystem/go-grpc-prometheus#14]
Hi,
*/metrics* are correctly setup for my gRPC server but when i've got an authenticated error, i don't see any metrics.
See: https://github.com/mwitkow/go-grpc-middleware/issues/16

Do you have any idea ? Thanks

**Comment by mwitkow** [comment]
Addressed inside mwitkow/go-grpc-middleware#16, it's a middleware chain ordering problem.
