### ISSUE TITLE
Please export more code

### ISSUE THREAD

**Issue by AlekSi** [grpc-ecosystem/go-grpc-prometheus#24]
Right now I use that code for unary RPC:
```go
// Unary adds context logger and Prometheus metrics to unary server RPC.
func Unary(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
    ctx = logger.Set(ctx, logger.MakeRequestID())
    return grpc_prometheus.UnaryServerInterceptor(ctx, req, info, handler)
}
```
It creates a new derived request with set logger and then calls your interceptor which calls handler. However, it is not possible to do the same for streams without copy&pasting half of that package. Please expose more types and functions to make this possible.

**Comment by brancz** [comment]
Any suggestions? Can you elaborate more on how you imagine this to work with streams and what you currently have to do?

**Comment by AlekSi** [comment]
Was able to achieve what I wanted with [grpc_middleware.WrappedServerStream ](https://godoc.org/github.com/grpc-ecosystem/go-grpc-middleware#WrappedServerStream).
