### ISSUE TITLE
Is it possible to expose metrics only client-side?

### ISSUE THREAD

**Issue by activeshadow** [grpc-ecosystem/go-grpc-prometheus#28]
The client-side example in the README shows how to add the client-side interceptors, but doesn't include anything about initializing the client-side metrics or exposing them via `promhttp.Handler`. I noticed in the docs that there's no client-side equivalent for the `grpc_prometheus.Register` function, so I'm curious if it's even possible to expose metrics only client-side?

I'm wanting to use this capability to instrument an instance of the `grpc-gateway` that I run, which from a gRPC perspective is client-side only. Perhaps for it to work I need to use it in the server-side gRPC microservices the `grpc-gateway` talks to as well, and the client-side metrics will be exposed there? If there's an example of using this w/ `grpc-gateway` that would be great too.

**Comment by brancz** [comment]
You can use the available functionality to create a new "ClientMetrics" struct and register it on any metrics registry you want, that way you'll get only client metrics.

**Comment by bzon** [comment]
@brancz can you provide an example?
