### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by hsaliak** [grpc-ecosystem/go-grpc-prometheus#38]
@mwitkow or any other author - there are outstanding PRs against this project, and no updates for a while. 
Is this unmaintained? 
Do let me know - If I do not hear back in a week, I will provide a PR to indicate that the project is unmaintained,, so that people with Open PRs are not in limbo..

**Comment by mwitkow** [comment]
Fair point, I've had a pretty long non-engineering stint in the last couple of months. While I found people from our company to look after [go-grpc-middleware](https://github.com/grpc-ecosystem/go-grpc-middleware), I completely forgot about this one.  

I've added @yifanzz and @domgreen to the list of maintainers as they are also looking after go-grpc-middleware.

**Comment by mwitkow** [comment]
@brancz, do you want to help out here as well? :)

**Comment by Bplotka** [comment]
I can help as well.

**Comment by hsaliak** [comment]
@mwitkow This is only normal in OSS and thanks a ton for all the valuable effort on this project so far. 
One immediate point of attention for new owners would be https://github.com/grpc-ecosystem/go-grpc-prometheus/pull/35 
I think this is straightforward and valuable to merge, but it's for the maintainers to make that call. :)

**Comment by brancz** [comment]
I'd be happy to help out as well!

**Comment by mwitkow** [comment]
Cool, added @Bplotka  (Thanos maintainer) and @branch (Prometheus maintainer) with write perms here.

**Comment by brancz** [comment]
@mwitkow  Just to make sure my handle is @brancz, not @Branch (I did get the invite, but just making sure it didn't also go to @Branch )

**Comment by brancz** [comment]
We've picked up the maintenance of this, so I'll close this issue.
