### ISSUE TITLE
Travis: go versions?

### ISSUE THREAD

**Issue by knweiss** [grpc-ecosystem/go-grpc-prometheus#48]
Two questions:

- Shouldn't we add the **two supported** (and therefore most important) Go versions go1.9 and go1.10 to Travis, too?
```
$ head .travis.yml -n 8
sudo: false
language: go
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - master

```
- What about removing old versions? If we drop go1.6 we could e.g. import package `context` instead of the old `golang.org/x/net/context` as it was integrated into the standard library in go1.7.

**Comment by brancz** [comment]
Adding 1.9 and 1.10 sounds good to me.

> If we drop go1.6 we could e.g. import package context instead of the old golang.org/x/net/context as it was integrated into the standard library in go1.7.

What does grpc use? It's probably ok to use the standard lib one by now.

**Comment by brancz** [comment]
In that case we should probably stick to it here as well.

**Comment by knweiss** [comment]
@brancz OTOH: Travis-CI of `github.com/prometheus/client_golang` requires at least go1.7 since September 2017.

Adding go1.9 and go1.10 in #50 (if it works).
