### ISSUE TITLE
Client Time Histogram for bidi_stream

### ISSUE THREAD

**Issue by davejohnston** [grpc-ecosystem/go-grpc-prometheus#59]
It looks like after adding EnableClientHandlingTimeHistogram() I can collect counters for unary rpc messages, but there is not reporting on bidirectional streams.

Is this intentional, or a bug?

**Comment by davejohnston** [comment]
I was hoping to be able to use it to calculate the average number of messages sent over the stream per second, over a period of time.

**Comment by brancz** [comment]
I think that's reasonable, but that would be accomplished with a counter, as you use the `rate` function over the monotonically increasing counter value, thus yielding the messages per second. This is already available with these metrics: https://github.com/grpc-ecosystem/go-grpc-prometheus/blob/c225b8c3b01faf2899099b768856a9e916e5087b/client_metrics.go#L44-L54

**Comment by davejohnston** [comment]
Thanks - looks like the irate() function with the above counter solves my issue.
