### ISSUE TITLE
Change context import to system context

### ISSUE THREAD

**Issue by vanship82** [grpc-ecosystem/go-grpc-prometheus#69]
https://github.com/grpc-ecosystem/go-grpc-prometheus/blob/c225b8c3b01faf2899099b768856a9e916e5087b/server_metrics.go#L5

It breaks the build with grpc v1.18.0

**Comment by brancz** [comment]
I'm happy with changing to the core package. Wdyt @bwplotka ?

**Comment by vanship82** [comment]
Thanks! Here is another one 👍 
https://github.com/grpc-ecosystem/go-grpc-prometheus/blob/68e3a13e41175110a447e67246a59873d6aca902/client_metrics.go#L7

**Comment by bwplotka** [comment]
I think the Golang compatibility is the key question here. We need to choose one (: 

Either deprecate old Golang (I think 1.6 or something?) or not allow grpc v1.18.0 ;p

I feel like a new release that goes with gRPC on golang compatiblity side is way to go with this. :+1:

**Comment by brancz** [comment]
Seems like we're in agreement :)
